{% set version = "4.0.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-caretensemble
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/caretEnsemble_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/caretEnsemble/caretEnsemble_{{ version }}.tar.gz
  sha256: eb2170f93088c5b3037896e0f1898c41cd01f81edd73105e899e88376a8b5fc7

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-caret
    - r-data.table
    - r-ggplot2
    - r-lattice
    - r-patchwork
    - r-pbapply
    - r-rlang
  run:
    - r-base
    - r-caret
    - r-data.table
    - r-ggplot2
    - r-lattice
    - r-patchwork
    - r-pbapply
    - r-rlang

test:
  commands:
    - $R -e "library('caretEnsemble')"           # [not win]
    - "\"%R%\" -e \"library('caretEnsemble')\""  # [win]

about:
  home: https://github.com/zachmayer/caretEnsemble
  license: MIT
  summary: 'Functions for creating ensembles of caret models: caretList() and caretStack().  caretList() is a convenience function for fitting multiple caret::train() models to the same dataset. caretStack() will make linear or non-linear combinations of these models, using a caret::train() model as a meta-model, and caretEnsemble()
    will make a robust linear combination of models using a GLM.'
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Encoding: UTF-8
# Package: caretEnsemble
# Type: Package
# Title: Ensembles of Caret Models
# Version: 2.0.1
# Date: 2019-12-11
# Authors@R: c(person(c("Zachary", "A."), "Deane-Mayer", role = c("aut", "cre"), email = "zach.mayer@gmail.com"), person(c("Jared", "E."), "Knowles", role=c("aut"), email="jknowles@gmail.com"))
# URL: https://github.com/zachmayer/caretEnsemble
# BugReports: https://github.com/zachmayer/caretEnsemble/issues
# Description: Functions for creating ensembles of caret models: caretList() and caretStack().  caretList() is a convenience function for fitting multiple caret::train() models to the same dataset. caretStack() will make linear or non-linear combinations of these models, using a caret::train() model as a meta-model, and caretEnsemble() will make a robust linear combination of models using a GLM.
# Depends: R (>= 3.2.0)
# Suggests: caTools, testthat, lintr, randomForest, glmnet, rpart, kernlab, nnet, e1071, ipred, pROC, knitr, mlbench, MASS, gbm, klaR, rmarkdown
# Imports: methods, pbapply, ggplot2, digest, plyr, lattice, gridExtra, data.table, caret
# License: MIT + file LICENSE
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-12-12 19:52:45 UTC; zach2
# Author: Zachary A. Deane-Mayer [aut, cre], Jared E. Knowles [aut]
# Maintainer: Zachary A. Deane-Mayer <zach.mayer@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-12-12 22:10:09 UTC
